### ISSUE TITLE
Unable to locate sitecore-hostswriter:9174-nanoserver-1809

### ISSUE THREAD

**Issue by pascalheller** [Sitecore/Sitecore.HabitatHome.Platform#184]
Hi,

I started to set up a new Habitat 9.3 demo using docker containers to show some marketeers some of the cool sitecore features.
There is only one thing left starting the application.

I cannot find the image for sitecore-hostswriter:9174-nanoserver-1809.

Has someone an idea where I can find this image.

Thanks a lot for your help.
Pascal

**Comment by bplasmeijer** [comment]
Hi @pascalheller 

We have this in our DevOps repository and will be shared soon on GitHub.

Workaround for now, comment out the hostwriter part in the docker-compose file and use https://github.com/gregolsky/whales-names 

Whales-names continuously update your local host file.

**Comment by pascalheller** [comment]
Hi @bplasmeijer,

I removed the hostwriter part from docker-compose file, installed and started whales.
The entries in my host file are updated on a regular base. That works fine.

But I silll have issues. The issue I am fighting with is, that the CM container for example cannot resolve the Sql-Server "sql" that is used insight the ConnectionStrings.config.

Exception Details: System.ComponentModel.Win32Exception: The network path was not found

Any idea for this?
Thanks.

**Comment by pascalheller** [comment]
Hi @bplasmeijer,

I solved the issue. I used the following docker-compose part and mounted my hosts file into every container. 
Then I synced all the unicorn projects, published everything and the demo was up and running. Don't understand why I hat to start the unicorn process manually. A colleague from me had all items without unsing unicorn. ?!?!? you can close the ticket. Thanks for your help

Best Regards
Pascal

```
  monitor:
    image: rahnemann/windows-hosts-writer:1.1-nanoserver-${NANOSERVER_VERSION}
    volumes:
      - C:/windows/system32/drivers/etc:C:\driversetc
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
    networks:
      - demo
```
